# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concentracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormaFarmaceutica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=200)),
                ('fecha_entrada', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_atc', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('factura', models.CharField(blank=True, max_length=50)),
                ('cantidad', models.IntegerField()),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.Inventario')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipioActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principios_activos', to='inventario.Concentracion')),
                ('forma_farmaceutica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principios_activos', to='inventario.FormaFarmaceutica')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principios_activos', to='inventario.Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Medicamento'), ('2', 'Dispositivos'), ('3', 'Producto Facial')], default='1', max_length=1)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('registro_invima', models.CharField(blank=True, max_length=200)),
                ('laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.Laboratorio')),
                ('principio_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.PrincipioActivo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('1', 'Entrada'), ('2', 'Salida'), ('3', 'Traslado')], default='1', max_length=1)),
                ('descripcion', models.CharField(max_length=100)),
                ('detalle', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.Unidad'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.TipoDeMovimiento'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='concentracion',
            field=models.ManyToManyField(related_name='concentracion', through='inventario.PrincipioActivo', to='inventario.Concentracion'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.ManyToManyField(related_name='forma_farmaceutica', through='inventario.PrincipioActivo', to='inventario.FormaFarmaceutica'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventario.Producto'),
        ),
    ]
