# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('organizacional', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('servicios', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioatencion',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='organizacional.Empleado'),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='organizacional.Sucursal'),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='agenda.Cita', verbose_name='cita'),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='organizacional.Empleado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='detalle_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='facturacion.DetalleFactura'),
        ),
        migrations.AddField(
            model_name='cita',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='servicios.Plan', verbose_name='entidad'),
        ),
        migrations.AddField(
            model_name='cita',
            name='formatos',
            field=models.ManyToManyField(related_name='citas', through='historias.Historia', to='historias.Formato'),
        ),
        migrations.AddField(
            model_name='cita',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='agenda.HorarioAtencion', verbose_name='horario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.Paciente', verbose_name='paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='servicios.Servicio', verbose_name='servicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio_prestado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.ServicioRealizar', verbose_name='servicio prestado'),
        ),
    ]
