# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20180828_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='servicio',
        ),
    ]
