# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20180910_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='servicio_prestado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.ServicioRealizar', verbose_name='servicio prestado'),
            preserve_default=False,
        ),
    ]
