# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20180910_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestado',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='motivo'),
        ),
    ]
