# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_historialestado_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestado',
            name='estado',
            field=models.CharField(choices=[('NC', 'No confirmada'), ('CO', 'Confirmada'), ('CU', 'Cumplida'), ('TE', 'Atendida'), ('NT', 'No atendida'), ('CA', 'Cancelada'), ('EX', 'Excusada'), ('NA', 'No asistio')], max_length=2, verbose_name='estado'),
        ),
    ]
