# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-24 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0001_initial'),
        ('agenda', '0006_auto_20181008_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='organizacional.Empleado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='organizacional.Sucursal'),
        ),
    ]
