# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-24 15:34
from __future__ import unicode_literals

from django.db.models import F
from django.db import migrations


class Migration(migrations.Migration):

    def horario_a_nuevos_campo_cita(apps, schema_editor):
        Cita = apps.get_model('agenda', 'Cita')

        for cita in Cita.objects.select_related('horario').all():
            cita.fin = cita.horario.end
            cita.inicio = cita.horario.start
            cita.medico = cita.horario.medico
            cita.sucursal = cita.horario.sucursal
            cita.save()

    dependencies = [
        ('agenda', '0007_auto_20181124_1033'),
    ]

    operations = [
        migrations.RunPython(horario_a_nuevos_campo_cita, reverse_code=migrations.RunPython.noop),
    ]
