# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-24 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_horario_cita_auto_20181124_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='organizacional.Empleado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='organizacional.Sucursal'),
        ),
    ]
