# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-24 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_auto_20181124_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['inicio'], 'permissions': [('puede_ver_agenda', 'Puede ver la agenda'), ('puede_agendar_cita', 'Puede agendar citas'), ('puede_ver_todas_citas', 'Puede ver todas las citas'), ('puede_cambiar_estado', 'Puede cambiar el estado de una cita'), ('puede_generar_indicadores_resolucion_256', 'Puede generar los indicadores para la resolucion 256')], 'verbose_name': 'cita', 'verbose_name_plural': 'citas'},
        ),
        migrations.RemoveField(
            model_name='cita',
            name='horario',
        ),
    ]
