# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_auto_20181124_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioatencion',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion_viejo', to='organizacional.Empleado'),
        ),
    ]
