# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_auto_20181124_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioatencion',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='horarioatencion',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='HorarioAtencion',
        ),
    ]
