# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_auto_20190503_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='detalle_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='facturacion.DetalleFactura'),
        ),
    ]
