# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-05 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_auto_20190615_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='autorizado_por',
            field=models.CharField(blank=True, max_length=100, verbose_name='autorizado por'),
        ),
    ]
