# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 22:29
from __future__ import unicode_literals

import common.models
from django.db import migrations, models
import django.db.models.deletion
import pacientes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0001_initial'),
        ('servicios', '0001_initial'),
        ('globales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('direccion', models.CharField(max_length=200, verbose_name='dirección')),
                ('telefono', models.CharField(max_length=200, verbose_name='teléfono')),
            ],
            options={
                'verbose_name': 'acompañate',
                'verbose_name_plural': 'acompañates',
            },
            bases=(common.models.UpdateModelMixin, pacientes.models.ParentescoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateField(auto_now_add=True, verbose_name='Fecha de la orden')),
                ('afiliacion', models.CharField(choices=[('C', 'Cotizante'), ('B', 'Beneficiario'), ('A', 'Subsidiado'), ('P', 'Particular'), ('V', 'Vinculado'), ('O', 'Otro')], max_length=1, verbose_name='afiliación')),
                ('tipo_usuario', models.CharField(choices=[('C', 'Contributivo'), ('A', 'Subsidiado'), ('V', 'Vinculado'), ('P', 'Particular'), ('O', 'Otro')], max_length=1, verbose_name='tipo de usuario')),
                ('anulada', models.BooleanField(default=False, verbose_name='anulada')),
                ('razon_anulacion', models.CharField(blank=True, max_length=200, verbose_name='razón de anulación')),
                ('asistio_acompanante', models.BooleanField(default=False, verbose_name='asistio con acompañante')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='organizacional.Institucion', verbose_name='entidad que prestará el servicio')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
            },
            bases=(common.models.UpdateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=150, verbose_name='primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=150, verbose_name='segundo nombre')),
                ('primer_apellido', models.CharField(max_length=150, verbose_name='primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=150, verbose_name='segundo apellido')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='género')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='fecha de ingreso')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('CD', 'Carnet diplomatico'), ('AN', 'Adulto sin identificar'), ('MN', 'Menor sin identificar'), ('NU', 'Número único de identificación')], max_length=2, verbose_name='tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='número de documento')),
                ('estado_civil', models.CharField(blank=True, choices=[('V', 'Viudo'), ('C', 'Casado'), ('S', 'Soltero'), ('D', 'Divociado'), ('UL', 'Unión libre')], max_length=2, verbose_name='estado civil')),
                ('zona', models.CharField(blank=True, choices=[('U', 'Urbano'), ('R', 'Rural')], max_length=1, verbose_name='zona')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=200, verbose_name='telefono')),
                ('celular', models.CharField(blank=True, max_length=200, verbose_name='celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, verbose_name='grupo sanguineo')),
                ('grupo_etnico', models.CharField(blank=True, choices=[('D', 'Desplazado'), ('I', 'Indigena'), ('N', 'Negro'), ('O', 'Otro')], max_length=1, verbose_name='grupo etnico')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('foto', models.ImageField(blank=True, upload_to=pacientes.models.paciente_foto_path, verbose_name='foto')),
                ('firma', models.ImageField(blank=True, upload_to=pacientes.models.paciente_firma_path, verbose_name='firma')),
                ('procedencia', models.CharField(blank=True, choices=[('IG', 'Instagram'), ('FB', 'Facebook'), ('IN', 'Internet'), ('R', 'Referido')], max_length=2, verbose_name='como se entero')),
                ('creado_el', models.DateField(auto_now_add=True)),
                ('nombre_responsable', models.CharField(blank=True, max_length=300, verbose_name='nombre completo del responsable')),
                ('direccion_responsable', models.CharField(blank=True, max_length=200, verbose_name='dirección del responsable')),
                ('telefono_responsable', models.CharField(blank=True, max_length=200, verbose_name='telefono del responsable')),
                ('identificacion_padre', models.CharField(blank=True, max_length=15, verbose_name='identificación del padre')),
                ('nombre_padre', models.CharField(blank=True, max_length=300, verbose_name='nombre completo del padre')),
                ('identificacion_madre', models.CharField(blank=True, max_length=15, verbose_name='identificación de la madre')),
                ('nombre_madre', models.CharField(blank=True, max_length=300, verbose_name='nombre completo de la madre')),
                ('lugar_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_nacidos_en', to='globales.Poblado', verbose_name='nacio en')),
                ('lugar_residencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_viven_en', to='globales.Poblado', verbose_name='donde vive')),
                ('profesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='globales.Profesion', verbose_name='profesión')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['primer_nombre', 'primer_apellido'],
            },
            bases=(pacientes.models.ParentescoMixin, common.models.UpdateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServicioRealizar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesiones', models.PositiveIntegerField(default=1, verbose_name='número de sesiones')),
                ('valor', models.DecimalField(decimal_places=15, help_text='Valor por sesión', max_digits=25, verbose_name='valor')),
                ('coopago', models.DecimalField(decimal_places=15, help_text='Coopago por sesión', max_digits=25, verbose_name='coopago/moderadora')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_realizar', to='pacientes.Orden', verbose_name='orden')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_realizar', to='servicios.Servicio', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'servicio a realizar',
                'verbose_name_plural': 'servicios a realizar',
            },
            bases=(common.models.UpdateModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='orden',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='pacientes.Paciente', verbose_name='paciente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='servicios.Plan', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='servicios',
            field=models.ManyToManyField(related_name='ordenes', through='pacientes.ServicioRealizar', to='servicios.Servicio', verbose_name='servicios'),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Orden', verbose_name='orden'),
        ),
    ]
