# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='parentesco_responsable',
            field=models.CharField(blank=True, choices=[('P', 'Padre'), ('M', 'Madre'), ('H', 'Hermano'), ('I', 'Hijo'), ('A', 'Abuelo'), ('T', 'Tio'), ('PR', 'Primo'), ('C', 'Conyugue'), ('AM', 'Amigo'), ('O', 'Otro')], max_length=3, verbose_name='parentesco del responsable'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('ME', 'Medico'), ('AM', 'Amigos'), ('PA', 'Paciente'), ('IG', 'Instagram'), ('FB', 'Facebook'), ('IN', 'Internet'), ('R', 'Referido')], max_length=2, verbose_name='como se entero'),
        ),
    ]
