# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20180905_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefono_madre',
            field=models.CharField(blank=True, max_length=200, verbose_name='telefono de la madre'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_padre',
            field=models.CharField(blank=True, max_length=200, verbose_name='telefono del padre'),
        ),
    ]
