# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20180910_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'permissions': [('puede_ver_orden', 'Puede ver la orden')], 'verbose_name': 'orden', 'verbose_name_plural': 'ordenes'},
        ),
    ]
