# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20180912_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='afiliacion',
            field=models.CharField(blank=True, choices=[('C', 'Cotizante'), ('B', 'Beneficiario'), ('A', 'Subsidiado'), ('P', 'Particular'), ('V', 'Vinculado'), ('O', 'Otro')], default='P', max_length=1, verbose_name='afiliación'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('C', 'Contributivo'), ('A', 'Subsidiado'), ('V', 'Vinculado'), ('P', 'Particular'), ('O', 'Otro')], default='P', max_length=1, verbose_name='tipo de usuario'),
        ),
    ]
