# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_acompanante_parentesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizar',
            name='estado',
            field=models.CharField(choices=[('NI', 'No iniciado'), ('IN', 'Iniciado'), ('TE', 'Terminado'), ('CA', 'Cancelado')], default='NI', max_length=2),
        ),
    ]
