# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0001_initial'),
        ('pacientes', '0009_serviciorealizar_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizar',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_recibidos', to='organizacional.Empleado'),
        ),
        migrations.AddField(
            model_name='serviciorealizar',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_verificados', to='organizacional.Empleado'),
        ),
    ]
