# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_auto_20181008_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizar',
            name='recibido_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciorealizar',
            name='verificado_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
