# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-17 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_auto_20181104_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'permissions': [('puede_ver_orden', 'Puede ver la orden'), ('puede_ver_orden_sin_paciente', 'Puede ver la orden sin que el paciente haya llegado a la cita')], 'verbose_name': 'orden', 'verbose_name_plural': 'ordenes'},
        ),
    ]
