# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def llenar_institucion_orden(apps, schema_editor):
        Orden = apps.get_model('pacientes', 'Orden')
        Institucion = apps.get_model('organizacional', 'Institucion')

        institucion = Institucion.objects.first()
        Orden.objects.filter(institucion__isnull=True).update(institucion=institucion)

    dependencies = [
        ('pacientes', '0014_auto_20181117_1310'),
        ('organizacional', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(llenar_institucion_orden, reverse_code=migrations.RunPython.noop),
    ]
