# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_institucion_orden_auto_20181120_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='organizacional.Institucion', verbose_name='entidad que prestará el servicio'),
        ),
    ]
