# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0002_horarioatencion'),
        ('pacientes', '0016_auto_20181120_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciorealizar',
            options={'ordering': ['id'], 'permissions': [('puede_recibir_asistencia', 'Puede recibir la asistencia entregada por los medicos'), ('puede_verificar_asistencia', 'Puede verificar la asistencia entregada por los medicos'), ('can_verificar_orden_inicio_tratamiento', 'Verificar los datos de la orden al inicio del tratamiento')], 'verbose_name': 'servicio a realizar', 'verbose_name_plural': 'servicios a realizar'},
        ),
        migrations.AddField(
            model_name='serviciorealizar',
            name='verificado_inicio_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciorealizar',
            name='verificado_inicio_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_verificados_inicio', to='organizacional.Empleado'),
        ),
    ]
