# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0017_auto_20190306_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'permissions': [('can_see_orden', 'Puede ver la orden'), ('can_edit_orden', 'Puede editar la orden despues de que ya se haya iniciado el tratamiento'), ('puede_ver_orden_sin_paciente', 'Puede ver la orden sin que el paciente haya llegado a la cita')], 'verbose_name': 'orden', 'verbose_name_plural': 'ordenes'},
        ),
    ]
