# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0018_auto_20190307_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciorealizar',
            options={'ordering': ['id'], 'permissions': [('puede_recibir_asistencia', 'Puede recibir la asistencia entregada por los medicos'), ('puede_verificar_asistencia', 'Puede verificar la asistencia entregada por los medicos'), ('can_verificar_orden_inicio_tratamiento', 'Verificar los datos de la orden al inicio del tratamiento'), ('can_recibir_pacientes_terminaron_tratamiento', 'Puede recibir los pacientes que terminaron tratamiento'), ('can_verificar_pacientes_terminaron_tratamiento', 'Puede verificar los pacientes que terminaron tratamiento')], 'verbose_name': 'servicio a realizar', 'verbose_name_plural': 'servicios a realizar'},
        ),
    ]
