# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0019_auto_20190321_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciorealizar',
            options={'ordering': ['id'], 'permissions': [('can_verificar_orden_inicio_tratamiento', 'Verificar los datos de la orden al inicio del tratamiento'), ('can_recibir_pacientes_terminaron_tratamiento', 'Puede recibir los pacientes que terminaron tratamiento'), ('can_verificar_pacientes_terminaron_tratamiento', 'Puede verificar los pacientes que terminaron tratamiento')], 'verbose_name': 'tratamiento', 'verbose_name_plural': 'tratamientos'},
        ),
    ]
