# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0021_auto_20190329_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizar',
            name='is_una_cita',
            field=models.BooleanField(default=False, help_text='Indica si el tratamiento se hace en una sola cita'),
        ),
    ]
