# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0012_institucion_footer_factura'),
        ('pacientes', '0022_serviciorealizar_is_una_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizar',
            name='verificado_inicio_admin_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciorealizar',
            name='verificado_inicio_admin_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_verificados_inicio_admin', to='organizacional.Empleado'),
        ),
    ]
