# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0024_auto_20190712_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['primer_nombre', 'primer_apellido'], 'permissions': [('can_add_paciente', 'Puede crear pacientes'), ('can_edit_paciente', 'Puede editar pacientes'), ('can_see_paciente', 'Puede ver los datos de un paciente')], 'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
    ]
