# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0026_auto_20190824_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='medico_ordena',
            field=models.CharField(blank=True, max_length=150, verbose_name='medico que ordena'),
        ),
    ]
