# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0027_orden_medico_ordena'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizar',
            name='num_sesiones_coopago',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='numero de sesiones por coopago'),
        ),
    ]
