# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin', models.TimeField()),
                ('inicio', models.TimeField()),
                ('dia', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado'), ('7', 'Domingo')], max_length=2)),
                ('con_descanso', models.BooleanField(default=False)),
                ('fin_descanso', models.TimeField(blank=True, null=True)),
                ('inicio_descanso', models.TimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='organizacional.Empleado')),
            ],
            options={
                'verbose_name': 'horario de atención',
                'verbose_name_plural': 'horarios de atención',
            },
        ),
    ]
