# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0002_horarioatencion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioatencion',
            options={'permissions': [('can_add_horario_atencion', 'Puede guardar el horario de atencion de los medicos')], 'verbose_name': 'horario de atención', 'verbose_name_plural': 'horarios de atención'},
        ),
    ]
