# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0003_auto_20190308_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioatencion',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='organizacional.Sucursal'),
        ),
    ]
