# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0005_add_sucursal_medico_horario_20190309_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioatencion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='organizacional.Sucursal'),
        ),
    ]
