# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0006_auto_20190309_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sucursal',
        ),
    ]
