# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0007_remove_empleado_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='codigo_contable_recibo',
            field=models.PositiveIntegerField(blank=True, help_text='Usado en la exportación de recibos de caja', null=True),
        ),
    ]
