# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 17:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0008_sucursal_codigo_contable_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='porcentaje_pago',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='porcentaje de pago'),
        ),
    ]
