# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0009_empleado_porcentaje_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='especialidad_historia',
            field=models.CharField(blank=True, max_length=100, verbose_name='especialidad historia'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='subtitulo_historia',
            field=models.CharField(blank=True, max_length=100, verbose_name='subtitulo en historia'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='titulo_historia',
            field=models.CharField(default='UMRI', max_length=100, verbose_name='titulo en historia'),
            preserve_default=False,
        ),
    ]
