# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0010_auto_20190515_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='firma_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituciones_firmo', to='organizacional.Empleado'),
        ),
    ]
