# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0011_institucion_firma_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='footer_factura',
            field=models.CharField(default='representante legal', max_length=100),
        ),
    ]
