# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-12 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0013_institucion_universidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('can_add_empleado', 'Puede agregar empleados')], 'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
    ]
