# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-16 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0014_auto_20190912_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='turnos',
            field=models.PositiveIntegerField(blank=True, help_text='Pacientes que puede atender al mismo tiempo', null=True, verbose_name='turnos'),
        ),
    ]
