# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-08 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0015_empleado_turnos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='turnos',
            new_name='atenciones_simultaneas',
        ),
    ]
