# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0017_auto_20191119_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('can_add_empleado', 'Puede agregar empleados'), ('can_ingresar_sin_restriccion', 'Puede ingresar sin ninguna restriccion')], 'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
    ]
