# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0001_initial'),
        ('globales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('razon_social', models.CharField(max_length=200, verbose_name='razón social')),
                ('nit', models.CharField(max_length=50, verbose_name='nit')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='dirección')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='telefono')),
                ('codigo', models.CharField(blank=True, max_length=100, verbose_name='código')),
                ('discriminar_iva', models.BooleanField(default=False, verbose_name='Discriminar IVA')),
                ('sesiones_autorizacion', models.IntegerField(blank=True, help_text='Indica el # de sesiones que le aplica la misma autorización. Si esta vació se usa la misma autorización para todas las sesiones.', null=True, verbose_name='sesiones por autorización')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='globales.Poblado', verbose_name='ciudad')),
                ('instituciones', models.ManyToManyField(related_name='clientes', to='organizacional.Institucion', verbose_name='instituciones')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='plan')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='servicios.Cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('codigo', models.CharField(blank=True, max_length=100, verbose_name='código')),
                ('abreviatura', models.CharField(max_length=100, verbose_name='abreviatura')),
                ('cups', models.CharField(blank=True, max_length=100, verbose_name='cups')),
                ('costo', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='costo')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=15, max_digits=25, verbose_name='valor')),
                ('coopago', models.DecimalField(decimal_places=15, max_digits=25, verbose_name='coopago')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='servicios.Plan', verbose_name='plan')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='servicios.Servicio', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'tarifa',
                'verbose_name_plural': 'tarifas',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('clase', models.CharField(choices=[('00', 'Otro'), ('01', 'Consulta'), ('06', 'Estancia'), ('07', 'Honorario'), ('08', 'Derecho de sala'), ('10', 'Banco de sangre'), ('12', 'Medicamento POS'), ('11', 'Prótesis y órtesis'), ('14', 'Traslado de paciente'), ('13', 'Medicamento no POS'), ('09', 'Materiales e insumos'), ('02', 'Procedimiento de diagnóstico'), ('04', 'Procedimiento terapéutico quirúrgico'), ('05', 'Procedimiento de promoción y prevención'), ('03', 'Procedimiento terapéutico no quirúrgico')], max_length=3, verbose_name='clase')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='servicios.Tipo', verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='plan',
            name='servicios',
            field=models.ManyToManyField(related_name='planes', through='servicios.Tarifa', to='servicios.Servicio', verbose_name='servicios'),
        ),
    ]
