# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='factura_paciente',
            field=models.BooleanField(default=False, verbose_name='Factura a nombre de paciente'),
        ),
    ]
