# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0001_initial'),
        ('servicios', '0002_cliente_factura_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='organizacional.Institucion'),
        ),
    ]
