# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 21:51
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    def llenar_institucion_tarifa(apps, schema_editor):
        Plan = apps.get_model('servicios', 'Plan')

        for plan in Plan.objects.all():
            institucion = plan.cliente.instituciones.first()
            plan.tarifas.all().update(institucion=institucion)

    dependencies = [
        ('organizacional', '0001_initial'),
        ('servicios', '0003_tarifa_institucion'),
    ]

    operations = [
        migrations.RunPython(llenar_institucion_tarifa, reverse_code=migrations.RunPython.noop),
    ]
