# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20181113_1651_llenar_institucion_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='organizacional.Institucion'),
        ),
    ]
