# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20181113_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='instituciones',
        ),
    ]
