# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20190322_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifa',
            options={'permissions': [('can_add_tarifa', 'Puede agregar tarifas')], 'verbose_name': 'tarifa', 'verbose_name_plural': 'tarifas'},
        ),
    ]
