# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0007_remove_empleado_sucursal'),
        ('servicios', '0008_auto_20190322_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='coopago',
            field=models.DecimalField(decimal_places=15, help_text='Valor del coopago con IVA', max_digits=25, verbose_name='coopago'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifa',
            unique_together=set([('servicio', 'plan', 'institucion')]),
        ),
    ]
