# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-04 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_auto_20190326_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='in_indicadores',
            field=models.BooleanField(default=True),
        ),
    ]
