# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_cliente_puc_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('EPS', 'EPS'), ('ARL', 'ARL'), ('MP', 'Prepagada'), ('OTRO', 'Otras entidades')], default='MP', max_length=5),
            preserve_default=False,
        ),
    ]
