# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0001_initial'),
        ('servicios', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=15, help_text='Valor unitario', max_digits=25, verbose_name='valor')),
                ('coopago', models.DecimalField(decimal_places=15, help_text='Coopago total', max_digits=25, verbose_name='coopago')),
                ('iva_coopago', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='IVA coopago')),
                ('coopago_bruto', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='coopago bruto')),
            ],
            options={
                'verbose_name': 'detalle de factura',
                'verbose_name_plural': 'detalles de factura',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='número')),
                ('fecha_fin', models.DateField(verbose_name='fecha fin')),
                ('fecha_inicio', models.DateField(verbose_name='fecha inicio')),
                ('fecha_expedicion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de expedicion')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='servicios.Cliente')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='organizacional.Institucion')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'permissions': [('puede_generar_facturas', 'Puede generar facturas'), ('puede_generar_rips', 'Puede generar rips'), ('puede_ver_facturas', 'Puede ver facturas')],
            },
        ),
        migrations.CreateModel(
            name='ReciboCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(choices=[('E', 'Efectivo'), ('T', 'Tarjeta'), ('C', 'Consignación')], max_length=2, verbose_name='forma de pago')),
                ('valor', models.DecimalField(decimal_places=15, max_digits=25, verbose_name='valor')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('detalle', models.TextField(blank=True, verbose_name='detalle')),
                ('servicio_prestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_caja', to='pacientes.ServicioRealizar', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'recibo de caja',
                'verbose_name_plural': 'recibos de caja',
            },
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='facturacion.Factura'),
        ),
    ]
