# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocaja',
            name='numero',
            field=models.IntegerField(default=1, verbose_name='número'),
            preserve_default=False,
        ),
    ]
