# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibocaja',
            options={'permissions': [('print_recibo', 'Puede imprimir recibos de caja')], 'verbose_name': 'recibo de caja', 'verbose_name_plural': 'recibos de caja'},
        ),
    ]
