# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_recibocaja_numero'),
        ('facturacion', '0002_auto_20180914_1811'),
    ]

    operations = [
    ]
