# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_auto_20181008_1736'),
        ('facturacion', '0003_merge_20180923_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='pacientes.Paciente'),
        ),
    ]
