# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_caja_detallecaja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'permissions': [('puede_cerrar_caja', 'Puede cerrar caja')], 'verbose_name': 'caja', 'verbose_name_plural': 'cajas'},
        ),
    ]
