# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_auto_20181107_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'permissions': [('puede_cerrar_caja', 'Puede cerrar caja'), ('puede_ver_todas_cajas', 'Puede ver todas las cajas')], 'verbose_name': 'caja', 'verbose_name_plural': 'cajas'},
        ),
    ]
