# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0001_initial'),
        ('facturacion', '0007_auto_20181108_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-fecha'], 'permissions': [('puede_cerrar_caja', 'Puede cerrar caja'), ('puede_ver_todas_cajas', 'Puede ver todas las cajas')], 'verbose_name': 'caja', 'verbose_name_plural': 'cajas'},
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='empleado',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='recibos_caja', to='organizacional.Empleado'),
            preserve_default=False,
        ),
    ]
