# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_auto_20181120_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='pagos',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=25, verbose_name='pagos'),
        ),
    ]
