# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0001_initial'),
        ('facturacion', '0014_caja_pagos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-fecha'], 'permissions': [('puede_cerrar_caja', 'Puede cerrar caja'), ('puede_ver_caja', 'Puede ver detalle de una caja'), ('puede_ver_todas_cajas', 'Puede ver todas las cajas'), ('puede_recibir_caja', 'Puede recibir el dinero del cierre de caja'), ('puede_verificar_caja', 'Puede verificar la caja con las transacciones'), ('puede_ver_transacciones_caja', 'Puede ver transacciones asociadas a una caja')], 'verbose_name': 'caja', 'verbose_name_plural': 'cajas'},
        ),
        migrations.AddField(
            model_name='caja',
            name='observaciones_verificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='verificacion_correcta',
            field=models.BooleanField(default=False, help_text='Indica si los valores son correctos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='verificado_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas_verificadas', to='organizacional.Empleado'),
        ),
    ]
