# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_auto_20181120_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='verificacion_correcta',
            field=models.BooleanField(default=True, help_text='Indica si los valores son correctos'),
        ),
    ]
