# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_auto_20181130_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'permissions': [('can_facturar', 'Puede facturar'), ('puede_generar_rips', 'Puede generar rips')], 'verbose_name': 'factura', 'verbose_name_plural': 'facturas'},
        ),
    ]
