# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_auto_20190322_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibocaja',
            options={'permissions': [('print_recibo', 'Puede imprimir recibos de caja'), ('can_contabilizar_recibo_caja', 'Puede contabilizar recibos de caja')], 'verbose_name': 'recibo de caja', 'verbose_name_plural': 'recibos de caja'},
        ),
    ]
