# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0010_auto_20190515_1630'),
        ('facturacion', '0020_auto_20190513_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='fecha inicio'),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together=set([('numero', 'institucion')]),
        ),
    ]
