# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0022_auto_20190523_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibocaja',
            options={'permissions': [('print_recibo', 'Puede imprimir recibos de caja'), ('can_see_recibos_caja', 'Puede ver los pagos de un paciente'), ('can_contabilizar_recibo_caja', 'Puede contabilizar recibos de caja')], 'verbose_name': 'recibo de caja', 'verbose_name_plural': 'recibos de caja'},
        ),
    ]
