# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-03 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0012_institucion_footer_factura'),
        ('facturacion', '0023_auto_20190701_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibocaja',
            options={'permissions': [('print_recibo', 'Puede imprimir recibos de caja'), ('can_see_recibos_caja', 'Puede ver los pagos de un paciente'), ('can_anular_recibos_caja', 'Puede anular pagos de pacientes'), ('can_contabilizar_recibo_caja', 'Puede contabilizar recibos de caja')], 'verbose_name': 'recibo de caja', 'verbose_name_plural': 'recibos de caja'},
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='anulado_el',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibos_caja_anulados', to='organizacional.Empleado'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='razon_anulacion',
            field=models.TextField(blank=True),
        ),
    ]
