# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-26 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0015_empleado_turnos'),
        ('facturacion', '0025_auto_20190828_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocaja',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibos_caja', to='organizacional.Sucursal'),
        ),
    ]
