# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-26 18:30
from __future__ import unicode_literals

from django.db import migrations

def add_sucursal_recibo(apps, schema_editor):
    ReciboCaja = apps.get_model('facturacion', 'ReciboCaja')
    # Yubissie - Sur
    ReciboCaja.objects.filter(empleado__cedula='32881087').update(sucursal=2)
    # Marta - Norte
    ReciboCaja.objects.filter(empleado__cedula='32748046').update(sucursal=1)
    
    for recibo in ReciboCaja.objects.exclude(empleado__cedula__in=['32881087', '32748046']):
        citas = recibo.servicio_prestado.citas.filter(inicio__date=recibo.fecha)
        if len(citas) == 0:
            citas = recibo.servicio_prestado.citas.all()
        
        recibo.sucursal = citas[0].sucursal
        recibo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0026_recibocaja_sucursal'),
    ]

    operations = [
        migrations.RunPython(add_sucursal_recibo, migrations.RunPython.noop),
    ]
