# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_cliente_tipo'),
        ('facturacion', '0028_auto_20190926_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroFacturaSiigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('EPS', 'EPS'), ('ARL', 'ARL'), ('MP', 'Prepagada'), ('OTRO', 'Otras entidades')], max_length=5)),
                ('cuenta_puc', models.CharField(max_length=100)),
                ('codigo_linea', models.CharField(max_length=5)),
                ('codigo_producto', models.CharField(max_length=5)),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_facturacion_siigo', to='servicios.Tipo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='parametrofacturasiigo',
            unique_together=set([('tipo_cliente', 'tipo_servicio')]),
        ),
    ]
