# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0017_auto_20191119_1144'),
        ('facturacion', '0030_auto_20191104_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='anulado_el',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_anuladas', to='organizacional.Empleado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='razon_anulacion',
            field=models.TextField(blank=True),
        ),
    ]
