# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 16:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0031_auto_20191119_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='citas_anuladas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
