# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-22 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0032_detallefactura_citas_anuladas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'permissions': [('can_facturar', 'Puede facturar'), ('can_anular_facturas', 'Puede anular facturas')], 'verbose_name': 'factura', 'verbose_name_plural': 'facturas'},
        ),
    ]
