# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-13 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_see_citas_paciente', 'Puede ver reporte citas por paciente'), ('can_see_relacion_recibos_caja', 'Puede ver relacion recibos de caja'), ('can_see_tratamientos_facturado_entidad', 'Puede ver reporte tratamientos facturados por entidad'), ('can_see_tratamientos_iniciados_profesional', 'Puede ver reporte tratamientos iniciados por profesional'), ('can_see_tratamientos_terminado_profesional', 'Puede ver reporte tratamientos terminados por profesional'), ('can_see_tratamientos_no_terminado_profesional', 'Puede ver reporte tratamientos no terminados por profesional')],
                'managed': False,
            },
        ),
    ]
