# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 22:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import historias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('organizacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=historias.models.archivo_adjunto_path, verbose_name='archivo')),
            ],
            options={
                'verbose_name': 'adjunto',
                'verbose_name_plural': 'adjuntos',
            },
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('contenido', django.contrib.postgres.fields.jsonb.JSONField()),
                ('valores_por_defecto', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('permiso', models.CharField(help_text='Permiso que indica si el usuario puede usar este formato para crear registros en la historia', max_length=100, verbose_name='permiso')),
                ('diagnostico', models.BooleanField(default=False, verbose_name='genera diagnostico')),
            ],
            options={
                'verbose_name': 'formato',
                'verbose_name_plural': 'formatos',
                'permissions': [('can_add_triage', 'Puede agregar triage'), ('can_add_consentimiento', 'Puede agregar consentimiento'), ('can_add_terapia_fisica', 'Puede agregar terapia fisica'), ('can_add_historia_clinica', 'Puede agregar historia clinica'), ('can_add_terapia_lenguaje', 'Puede agregar terapia lenguaje'), ('can_add_nota_enfermeria', 'Puede agregar nota de enfermeria'), ('can_add_terapia_ocupacional', 'Puede agregar terapia ocupacional'), ('can_add_terapia_respiratoria', 'Puede agregar terapia respiratoria'), ('can_add_historia_nutricional', 'Puede agregar historia nutricional'), ('can_add_historia_clinica_estetica', 'Puede agregar historia clinica estetica'), ('can_add_historia_clinica_traccion', 'Puede agregar historia clinica de traccion'), ('can_add_historia_drenaje_linfatico', 'Puede agregar historia de drenaje linfatico'), ('can_add_historia_clinica_psicologica', 'Puede agregar historia clinica psicologica'), ('can_add_historia_clinica_estetica_corporal', 'Puede agregar historia clinica estetica corporal')],
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('contenido', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('terminada', models.BooleanField(default=False)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='agenda.Cita', verbose_name='cita')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='historias.Formato', verbose_name='formato')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='organizacional.Empleado', verbose_name='medico')),
            ],
            options={
                'verbose_name': 'historia',
                'verbose_name_plural': 'historias',
                'ordering': ['-fecha'],
                'permissions': [('puede_editar_historias', 'Puede editar historias'), ('puede_agregar_triage', 'Puede agregar triage'), ('print_historias', 'Puede imprimir historias'), ('puede_ver_historias', 'Puede ver historias')],
            },
        ),
        migrations.AddField(
            model_name='adjunto',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='historias.Historia', verbose_name='historia'),
        ),
    ]
