# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0005_auto_20190130_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historia',
            options={'ordering': ['-fecha'], 'permissions': [('puede_ver_historias', 'Puede ver historias'), ('puede_agregar_triage', 'Puede agregar triage'), ('puede_editar_historias', 'Puede editar historias'), ('puede_imprimir_historias', 'Puede imprimir historias')], 'verbose_name': 'historia', 'verbose_name_plural': 'historias'},
        ),
    ]
