# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0010_auto_20191025_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
