# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0013_auto_20191202_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historia',
            options={'ordering': ['-fecha'], 'permissions': [('puede_ver_historias', 'Puede ver historias'), ('puede_agregar_triage', 'Puede agregar triage'), ('puede_editar_historias', 'Puede editar historias'), ('puede_imprimir_historias', 'Puede imprimir historias'), ('can_see_historias', 'Puede ver historias de un paciente'), ('can_edit_historias', 'Puede editar historias de un paciente'), ('can_delete_historias', 'Puede eliminar historias de un paciente')], 'verbose_name': 'historia', 'verbose_name_plural': 'historias'},
        ),
    ]
