# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0002_auto_20181111_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rips',
            name='tipo',
            field=models.CharField(choices=[('CO', 'Consulta'), ('PR', 'Procedimiento')], max_length=2, unique=True),
        ),
    ]
