# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0010_auto_20190515_1630'),
        ('parametrizacion', '0003_auto_20181111_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacional.Empleado')),
            ],
            options={
                'verbose_name': 'facturacion',
                'verbose_name_plural': 'facturacion',
            },
        ),
    ]
