# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0004_facturacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacion',
            name='firma',
        ),
        migrations.DeleteModel(
            name='Facturacion',
        ),
    ]
