# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-16 16:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0005_auto_20190529_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion_256', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='tipos de registro que no aplican para el tenant', null=True, size=None)),
            ],
            options={
                'verbose_name': 'configuración',
                'verbose_name_plural': 'configuraciones',
            },
        ),
    ]
